# Custom Language File for Launcher Customizer

[ejs.app]
title = "큐티"

[ejs.landing]
mediaGitHubURL = "https://s00-4.gitbook.io/s/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/jex5TPBtZ2"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/Cute"
supportLink = "https://github.com/CustomLauncherLab/Cute/issues"

[ejs.welcome]
welcomeHeader = ""
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."